POST http://localhost:9001/device/gateway
Content-Type: application/json

{
  "projectID": 1,
  "ip": "192.168.0.1",
  "mqtt": "192.168.1.1",
  "port": 1883,
  "mode": true,
  "virtualIP": "192.168.0.2",
  "state": true
}

###

POST http://localhost:9001/sensor
Content-Type: application/json

{
  "projectID": 1,
  "scannerID": 5,
  "mac": "AA:BB:CC:DD:EE:FF",
  "provider": "AERIX",
  "model": "T435",
  "variable": true,
  "value": 2,
  "min": 0,
  "max": 10
}

###

POST http://localhost:9001/device/scanner
Content-Type: application/json

{
  "projectID": 1,
  "ip": "192.168.0.99",
  "mqttIP": "192.168.0.214",
  "mqttPORT": "1883",
  "mqttTOPIC": "tharx/test",
  "name": "가상스캐너1",
  "mode": false,
  "enable": true,
  "parsing": true,
  "scanInterval": 5,
  "scanDuration": 5
}

###

PATCH http://localhost:9001/device/scanner
Content-Type: application/json

{
  "id": 2,
  "projectID": 1,
  "ip": "192.168.0.99",
  "mqtt": "192.168.0.214",
  "port": "1883",
  "topic": "tharx/*",
  "name": "가상스캐너2",
  "mode": false,
  "enable": true,
  "parsing": true,
  "scanDuration": 5
}

###

PATCH http://localhost:9001/sensor
Content-Type: application/json

{
  "id": 2,
  "projectID": 1,
  "scannerID": 1,
  "mac": "AA:BB:CC:DD:EE:F1",
  "provider": "AERIX",
  "model": "T435",
  "variable": true,
  "value": 9,
  "min": 0,
  "max": 10
}

###

DELETE http://localhost:9001/device/scanner/1
Accept: application/json

###

DELETE http://localhost:9001/device/scanner/1
Accept: application/json

###

DELETE http://localhost:9001/project/1
Accept: application/json

###

GET http://112.175.232.200:9001/project
Accept: application/json


###

PATCH http://localhost:9001/project
Content-Type: application/json

{
  "id": 1,
  "name": "AERIX2222",
  "mode": true
}

###

PATCH http://localhost:9001/project/mode
Content-Type: application/json

{
  "id": 1,
  "mode": false
}

###

POST http://localhost:9001/project
Content-Type: application/json

{
  "name": "AERIX2222"
}


###

POST http://localhost:9001/project
Content-Type: application/json

{
  "name": "AERIX2222"
}

###

POST http://localhost:9001/sensor
Accept: application/json

###

GET http://112.175.232.200:9001/sensor
Accept: application/json

###

POST http://localhost:9001/bluetooth
Accept: application/json

###

DELETE http://localhost:9001/project/1
Accept: application/json

###
PATCH http://localhost:9001/project/mode
Content-Type: application/json

{
  "id": 10,
  "mode": true
}

###

GET http://localhost:9001/device/10
Accept: application/json

###

GET http://112.175.232.200:9001/mqtt/packet
Accept: application/json

###

GET http://localhost:9001/device/scanner
Accept: application/json

###

POST http://112.175.232.200:3001/mqtt
Accept: application/json

###

GET http://localhost:9001/test?id=1&mode=true
Accept: application/json

###
